version: '3.8'

services:
  backend:
    image: ghcr.io/OWNER_ORG/smartswipe-backend:latest
    env_file:
      - .env
    restart: always
    ports:
      - "80:8000"
    depends_on:
      - db
    volumes:
      - pgdata:/var/lib/postgresql/data

  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata: 